# Managed by dotfiles (stow). Edit in-repo: dotfiles/starship/.config/starship/starship.toml

# Keep prompt readable and informative without being noisy.
# You can tune or add modules as you see fit.

# Show a distinct prompt symbol per vi mode.
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold blue)"

# Google Cloud Platform (GCP) context (project)
[gcloud]
disabled = false
format = "[$symbol$project]($style) "
symbol = "☁️  "
style = "bold blue"

# Kubernetes context and namespace
[kubernetes]
disabled = false
format = "[$context(\\($namespace\\))]($style) "
style = "bold purple"
# Example styling by context. Add your real patterns if desired.
contexts = [
  { context_pattern = "gke_.*", style = "bold green" },
  { context_pattern = "kind-.*", style = "bold yellow" },
  { context_pattern = "minikube", style = "bold cyan" }
]

# Optional: keep the prompt compact by trimming deep directories.
[directory]
truncate_to_repo = true
truncation_length = 3
style = "bold cyan"

# Helpful VCS info without being too busy.
[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold magenta"

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style) )"
conflicted = " "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = " "
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = " "

# Runtime versions for your stack (auto-hides if not relevant in a repo).
[nodejs]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold green"

[golang]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold cyan"

[rust]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold red"

[swift]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold 214"

# Timing for slow commands integrates with your REPORTTIME shell setting nicely.
[cmd_duration]
min_time = 2000
format = "[⏱ $duration]($style) "
style = "bold yellow"

# Add a newline before the start of the prompt for clarity (default: true).
add_newline = true
